services:
  frontend:
    build:
      context: ./
      dockerfile: dockerfile
    image: matteoskix/todoapp:latest
    ports:
    - "3000:3000"
    depends_on:
      - mysql
    environment:
      DB_HOST:
      DB_USER:
      DB_PASSWORD:
      DB_DATABASE:

  mysql:
    image: mysql:5.7
    restart: always
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: